export type Car = {
  id: number;
  name: string;
  tag: string;
  seats: number;
  transmission: string;
  price: number;
  horsepower: number;
  fuel_consumption: string;
  image: string;
};

export const carData: Car[] = [
  {
    id: 1,
    name: "Golf",
    tag: "1.4 TSI",
    seats: 5,
    transmission: "Auto",
    price: 23000,
    horsepower: 147,
    fuel_consumption: "6.0 L/100 km",
    image: "/cars/car_1.png",
  },

  {
    id: 2,
    name: "Golf",
    tag: "GTI",
    seats: 5,
    transmission: "Auto",
    price: 35000,
    horsepower: 228,
    fuel_consumption: "7.0 L/100 km",
    image: "/cars/car_2.png",
  },

  {
    id: 3,
    name: "Passat",
    tag: "2.0 TSI",
    seats: 5,
    transmission: "Auto",
    price: 28000,
    horsepower: 174,
    fuel_consumption: "6.5 L/100 km",
    image: "/cars/car_3.png",
  },
  {
    id: 4,
    name: "Passat",
    tag: "R-Line",
    seats: 5,
    transmission: "Manual",
    price: 33000,
    horsepower: 220,
    fuel_consumption: "7.5 L/100 km",
    image: "/cars/car_4.png",
  },
  {
    id: 5,
    name: "Tiguan",
    tag: "S",
    seats: 5,
    transmission: "Auto",
    price: 25000,
    horsepower: 184,
    fuel_consumption: "8.0 L/100 km",
    image: "/cars/car_5.png",
  },
  {
    id: 6,
    name: "Tiguan",
    tag: "SEL",
    seats: 5,
    transmission: "Manual",
    price: 34000,
    horsepower: 220,
    fuel_consumption: "8.5 L/100 km",
    image: "/cars/car_6.png",
  },
  {
    id: 7,
    name: "Jetta",
    tag: "S",
    seats: 5,
    transmission: "Auto",
    price: 20000,
    horsepower: 147,
    fuel_consumption: "6.0 L/100 km",
    image: "/cars/car_7.png",
  },
  {
    id: 8,
    name: "Jetta",
    tag: "GLI",
    seats: 5,
    transmission: "Manual",
    price: 29000,
    horsepower: 228,
    fuel_consumption: "7.5 L/100 km",
    image: "/cars/car_8.png",
  },
  {
    id: 9,
    name: "Golf",
    tag: "R",
    seats: 5,
    transmission: "Auto",
    price: 45000,
    horsepower: 315,
    fuel_consumption: "8.0 L/100 km",
    image: "/cars/car_9.png",
  },
  {
    id: 10,
    name: "Passat",
    tag: "SE",
    seats: 5,
    transmission: "Auto",
    price: 31000,
    horsepower: 190,
    fuel_consumption: "7.0 L/100 km",
    image: "/cars/car_10.png",
  },
  {
    id: 11,
    name: "Tiguan",
    tag: "R-Line",
    seats: 5,
    transmission: "Manual",
    price: 37000,
    horsepower: 235,
    fuel_consumption: "9.0 L/100 km",
    image: "/cars/car_11.png",
  },

  {
    id: 12,
    name: "Jetta",
    tag: "SEL",
    seats: 5,
    price: 24000,
    horsepower: 158,
    fuel_consumption: "6.5 L/100 km",
    transmission: "Auto",
    image: "/cars/car_12.png",
  },
  {
    id: 13,
    name: "Golf",
    tag: "Alltrack",
    seats: 5,
    transmission: "Auto",
    price: 28000,
    horsepower: 170,
    fuel_consumption: "6.5 L/100 km",
    image: "/cars/car_13.png",
  },
  {
    id: 14,
    name: "Tiguan",
    tag: "Comfortline",
    seats: 5,
    transmission: "Auto",
    price: 27000,
    horsepower: 200,
    fuel_consumption: "8.0 L/100 km",
    image: "/cars/car_14.png",
  },
  {
    id: 15,
    name: "Tiguan",
    tag: "Highline",
    seats: 5,
    transmission: "Manual",
    price: 36000,
    horsepower: 240,
    fuel_consumption: "8.8 L/100 km",
    image: "/cars/car_15.png",
  },
];
